version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
